### ISSUE TITLE
感谢大佬，稍微改了一下挂华为云上了，非常好用

### ISSUE THREAD

**Issue by Peace2F** [Maojuan-lang/SenKongDao#5]
就是不太理解为啥读cookie文件那段用的r+，华为云一直报无权限修改，后来改成r就好了

**Comment by Maojuan-lang** [comment]
r是只读权限，r+是读写权限，在r权限的情况下无法修改文件，检查自己用户的权限后再赋予文件权限进行修改操作。

更多信息可以搜索常用命令 chmod的用法。
