### ISSUE TITLE
森空岛已经禁止低版本签到，需要修改

### ISSUE THREAD

**Issue by HYY1116** [Maojuan-lang/SenKongDao#6]

**Comment by Maojuan-lang** [comment]
注意到了，之前是模拟旧版本签到，粗略看了下现在新版本可能加密了参数，我这边暂时没有精力去解析。

**Comment by enpitsuLin** [comment]
抓包看到了

<img width="522" alt="image" src="https://github.com/Maojuan-lang/SenKongDao/assets/29378026/6dde98e2-97b4-4ecc-b505-4416a92b853d">

查阅一些资料感觉是用了[阿里云WAFApp防护](https://help.aliyun.com/document_detail/160272.html?spm=a2c4g.256569.0.0.24997c47DZBaJR)然后给套了个壳，没有安全方面大佬帮忙应该不太好搞了

YJ 干啥啥不行，防护搞那么好😅

**Comment by HYY1116** [comment]
https://gitee.com/bulbasaur123/skyland-auto-sign#sign-heade
这里有个新的签到头解决方案，但是我不知道该咋写，用这个方法弄出来的请求头确实是可以签到的

**Comment by xxyz30** [comment]
https://gitee.com/FancyCabbage/skyland-auto-sign#sign-header
现成的写法

**Comment by Maojuan-lang** [comment]
直接引用了

> https://gitee.com/FancyCabbage/skyland-auto-sign#sign-header 现成的写法

大佬牛蛙
